jobs:
  - name: test
    serial: true
    plan:
    - get: src
      trigger: true
    - get: build-timer
      trigger: true
    - task: test
      file: src/ci/tasks/unit-test.yml
    - task: integration-test
      file: src/ci/tasks/integration-test.yml
      params:
        PROJECT_ID: ((integration-test-project-id))
        TOPIC_NAME: ((integration-test-topic))
        SUBSCRIPTION_NAME: ((integration-test-subscription))
        SERVICE_ACCOUNT: ((integration-test-service-account-json))
  - name: build
    build_logs_to_retain: 50
    plan:
    - get: src
      passed: [test]
      trigger: true
    - task: build
      file: src/ci/tasks/build.yml
  - name: build-latest
    build_logs_to_retain: 100
    plan:
    - get: src
      passed: [test]
      trigger: true
    - task: build
      file: src/ci/tasks/build-latest.yml
  - name: build-releases
    build_logs_to_retain: 50
    interruptible: true
    plan:
    - get: src
      passed: [test]
      trigger: true
    - task: build-releases
      file: src/ci/tasks/build-releases.yml

resources:
  - name: src
    type: git
    source:
      uri: ((repository-url))
      branch: ((repository-branch))
  - name: build-timer
    type: time
    source:
      interval: ((minimum-build-interval))
