# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - make clean
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  hooks:
    post: make dashboards
checksum:
  name_template: 'checksums.txt'
project_name: pubsubbeat
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
archives:
- wrap_in_directory: true
  files:
  - README.md
  - NOTICE
  - LICENSE
  - fields.yml
  - pubsubbeat.yml
  - pubsubbeat.reference.yml
  - dashboards/**/*
