language: go

go:
  - 1.13.x

go_import_path: github.com/GoogleCloudPlatform/pubsubbeat

env:
  - GO111MODULE=on

before_install:
  - travis_retry go mod download

script:
  - make test
  - make build
  - ls -l pubsubbeat
